name: Deploy to gh-pages

on:
  push:
    branches:
      - master  # Adjust the branch name to the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to gh-pages
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git branch -a  # Optional: Display branches for debugging purposes
        git checkout gh-pages || git checkout --orphan gh-pages
        git rm -rf .
        mv ./your_directory/* ./
        git add .
        git commit -m 'Update gh-pages'
        git push origin gh-pages
