name: Deploy to gh-pages and Create Repos

on:
  push:
    branches:
      - master  # Adjust the branch name to the branch you want to trigger the deployment

jobs:
  deploy_and_create_repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to gh-pages
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git branch -a  # Optional: Display branches for debugging purposes
          git checkout gh-pages || git checkout --orphan gh-pages
          git add .
          git commit -m 'Update gh-pages'
          git push origin gh-pages -f

      - name: Create Repos
        run: |
          #Hymnals=($(yq r hymnals.yaml hymnals[*]))
          #for hymnal in "${Hymnals[@]}"; do
          cat hymnals.yaml
          IFS=$'\n' read -d '' -r -a hymnals < hymnals.yaml
          for hymnal in "${hymnals[@]}"; do
            echo $hymnal
            # REPO_NAME=$(echo "$hymnal" | sed 's/-/_/g')  # Replace hyphens with underscores for valid repository names
            REPO_NAME="$hymnal"
            ORG_NAME=${{ github.repository_owner }}

            # Create the new repository using GitHub API
            curl -X POST \
              -H "Authorization: token ${{ secrets.CREATE_AH_REPOS }}" \
              -H "Content-Type: application/json" \
              -d "{\"name\":\"$REPO_NAME\", \"private\":false,\"has_issues\":true,\"has_projects\":true,\"has_wiki\":true}" \
              "https://api.github.com/orgs/$ORG_NAME/repos"
          done
