name: Deploy to gh-pages

on:
  push:
    branches:
      - master  # Adjust the branch name to the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to gh-pages
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git branch -a  # Optional: Display branches for debugging purposes
        git checkout gh-pages || git checkout --orphan gh-pages
        #git rm -rf .
        #mv ./your_directory/* ./
        git add .
        git commit -m 'Update gh-pages'
        git push origin gh-pages -f
    - name: Create new repository
      run: |
        REPO_NAME="new-repo-name"  # Replace this with the desired repository name
        echo $REPO_NAME
        # ORG_NAME="adventHymnals"  # Replace this with your GitHub username or organization name
        ORG_NAME=$(echo "${{ env.GITHUB_REPOSITORY }}" | cut -d / -f 1)
        echo $ORG_NAME
        # Create the new repository using GitHub API
        curl -X POST \
          -H "Authorization: token ${{ secrets.CREATE_AH_REPOS }}" \
          -H "Content-Type: application/json" \
          -d "{\"name\":\"$REPO_NAME\"}" \
          "https://api.github.com/orgs/$ORG_NAME/repos"
        echo "$ORG_NAME"
